Vagrant.configure("2") do |config|
  name = "bmoudachS"
  ip = "192.168.56.110"

  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 6
    libvirt.uri = "qemu:///system"
    libvirt.driver = "kvm"
  end

  config.vm.define name do |vm|
    vm.vm.hostname = name
    vm.vm.network "private_network", ip: ip

    vm.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end